### ISSUE TITLE
Disable/enable deployments based on env

### ISSUE THREAD

**Issue by pcmaffey** [astronomerio/houston-api#23]
So that CRUD on deployments can happen from localhost without actually trying to provision instance.

Is currently manually turned off.

**Comment by cwurtz** [comment]
We should mock the entire commander client so we can stub out the responses if an ENV is enabled, that way to we don't have to update everywhere data from commander is used, just prevent any interaction with it to begin with

**Comment by cwurtz** [comment]
All commander calls were updated in 0.4.x to console.log what they would do if `process.env != "production"`.
