### ISSUE TITLE
Create models and operations for service accounts in Houston

### ISSUE THREAD

**Issue by cwurtz** [astronomerio/houston-api#31]
@cwurtz commented on [Wed Jun 06 2018](https://github.com/astronomerio/astronomer/issues/115)

Create models for `service_accounts`, and `service_account_role_map`.

Create gql operations for:
serviceAccounts(serviceAccountUuid, entityType, entityUuid, category)
createServiceAccount(label, entityType, entityUuid, roles, category)
updateServiceAccount(serviceAccountUuid, payload)
deleteServiceAccount(serviceAccountUuid)

**Comment by schnie** [comment]
@cwurtz we're getting a lot of requests for this. Have we made any progress on these operations yet? Thinking about slotting it into the 3.4 release.

**Comment by schnie** [comment]
Closing this in favor of #41
