### ISSUE TITLE
Enable Additional OAuth Methods

### ISSUE THREAD

**Issue by gregbrunk** [astronomerio/houston-api#37]
As a user who may not have a google account or does not prefer that method, I would like additional methods OAuth methods to choose from.

_Think at a minimum this would include Github. @cwurtz: please provide additional details for the methods you choose to include here._

**Comment by cwurtz** [comment]
We chose Google OAuth first to cover the most ground.  The system is setup to support multiple OAuth providers, we just have to pick and choose when to add support.

Additionally, we are adding auth0 support this sprint, which supports pretty much any OAuth provider.   However the free auth0 account (one we'll use by default in Astronomer EE) only supports 2 options in that tier.  So we'll probably go with Google & Github to hopefully cover the maximum number of users.  Should a customer not be covered by Google/Github, they can just use user/pass auth.

Haven't gotten far enough into it yet, but I believe the process for auth'ing with auth0 under our account we'll distribute with by default will be different than if they want to swap out for their own auth0 account.  Need to do more research into that, depending how how long it takes may not ship this release with allowing EE customers to bring their own auth0 account.
