### ISSUE TITLE
Signup/Login url for Google OAuth is incorrect

### ISSUE THREAD

**Issue by license2e** [astronomerio/houston-api#59]
It always redirects to this url: `redirect_uri=https%3A%2F%2Fredirect.astronomer.io` instead of going to what is asked to be configured in this guide: https://www.astronomer.io/guides/install-google-oauth/ (ex. `https://app.astro.yourdomain.com/oauth/google`)

It is set to `redirect.astronomer.io` inside the `redirectUrl` function: https://github.com/astronomerio/houston-api/blob/d1b6307642f361d3477a180fc99e70457db68337/src/utils/auth_strategies.js#L131-L133

But the bug seems to be due to the Helm chart templates for `houston`:
```
            - name: AUTH0_CUSTOM
              value: {{ ne .Values.auth.auth0.baseDomain "astronomerio.auth0.com" | quote }}
```
https://github.com/astronomerio/helm.astronomer.io/blob/master/charts/astronomer/templates/houston/houston-deployment.yaml#L107-L108

Which requires the `baseDomain` to be set to the following as a workaround, even if `Auth0` is disabled:
```
astronomer:
  auth:
    auth0:
      enabled: false
      baseDomain: "mycompany.auth0.com"
```

But then, it still redirects to the incorrect URL: `&redirect_uri=https%3A%2F%2Fhouson.astro.yourdomain.com%2Foauth_redirect` instead of `https://app.astro.yourdomain.com/oauth/google` as specified in the guide.

Note: adding the url `https://houson.astro.yourdomain.com/oauth_redirect` to Google OAuth then works correctly...

Also, just changing the url in the browser to: `&redirect_uri=https%3A%2F%2Fapp.astro.yourdomain.com%2Foauth%2Fgoogle` leads to an error page.

**Comment by license2e** [comment]
Changed the documentation (until the redirect_url is changed) in this PR: https://github.com/astronomerio/airflow-guides/pull/54

**Comment by cwurtz** [comment]
Thanks for reporting the bug, sorry you had to spend time tracking it down.  I'll get a fix in that'll go out in the next release.

The docs are indeed out of date, when we added auth0 support, the redirects were converted into houston for simplicity.  The `https://houson.astro.yourdomain.com/oauth_redirect` is the correct redirect at this point in time.
