### ISSUE TITLE
Solidify Postgres User Permissions

### ISSUE THREAD

**Issue by andscoop** [astronomerio/houston-api#9]
Need to nail down exact user permissions needed by all Postgres users. This includes the `houston`/`airflow` connection used to create users during deployments as well as all users created during a deployment.

I will update once I determine the correct permissions needed by the core `houston`/`airflow` user. 

In the meantime the following permissions resolve issues around the users created with the new deployments.

```
GRANT USAGE ON SCHEMA airflow to [release_name]_airflow;
GRANT CREATE ON SCHEMA airflow to [release_name]_airflow;
```

**Comment by andscoop** [comment]
Ran into this one again today - it appears that the schemas were also not being created. So it was necessary to manually create airflow, grafana and celery schemas.

Note that this does not affect all postgres installs, so far it has affected compose and google cloud sql IIRC.

**Comment by cwurtz** [comment]
This should have been taken care of in an 0.4.x release
